//Import the functions you need. Read the firebase docs or ask if you're not sure which ones you need.
//You will generally always need collection
import {
  collection,
  doc,
  setDoc,
  serverTimestamp,
} from "https://www.gstatic.com/firebasejs/9.8.2/firebase-firestore.js";
//import the database instance
import { db } from "../firebaseconfig.js";

//we are exporting this function to use in app.js. The default part is optional but I see it often and it seems to be common practice. It allows you to name the import anything you want AND forces you to omit the {} when importing
export default async function submitDew(title, description, notes) {
  //docRef is a reference to the collection stored in a const
  const docRef = doc(collection(db, "dews"));
  //this is called a try/catch block. It will "try" the code you want to run. If there is an error it will be stored in an error object and the "catch" block will run. If there are no errors it will be skipped.
  try {
    //setDoc is a firebase function that allows us to add documents to the database
    await setDoc(docRef, {
      title,
      description,
      notes,
      //this is a unique id that is generated by firebase
      id: docRef.id,
      //this is a timestamp that we will use to order our dews
      createdAt: serverTimestamp(),
    });
  } catch (error) {
    console.log(error);
  }
}
